services:
  seachess-api:
    build: ./server
    ports:
      - "127.0.0.1:5039:5039" # Chỉ mở port cho Nginx trên host (localhost) gọi vào
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - ConnectionStrings__RedisConnection=redis:6379
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - JwtSettings__Issuer=SeaChessAPI
      - JwtSettings__Audience=SeaChessClient
      - ASPNETCORE_ENVIRONMENT=Production
      - Stockfish__Path=stockfish
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379" # Redis cũng chỉ nên nội bộ
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: