@host = http://localhost:5039

### Health check
# GET {{host}}/health

# ### Register
# POST {{host}}/api/Auth/register
# Content-Type: application/json

# {
#   "Username": "test",
#   "Displayname": "test",
#   "Email": "test@gmail.com",
#   "Password": "123456"
# }

# ### Login
POST {{host}}/api/Auth/login
Content-Type: application/json

{
  "Username": "test",
  "Password": "123456"
}